package cc.squall.relapse.utils.LWJGL.input;

import cc.squall.relapse.utils.datatypes.collections.BiMap;
import lombok.Getter;
import net.minecraft.client.Minecraft;
import net.minecraft.client.Options;

public class KeyUtil {

    private static final BiMap<String, String> KEYCODE_MAP = new KeyUtil().getKeycodeMap();

    public static String capitalize(String s) {
        if (s == null || s.isEmpty()) return s;
        return Character.toUpperCase(s.charAt(0)) + s.substring(1).toLowerCase();
    }

    public BiMap<String, String> getKeycodeMap() {
        BiMap<String, String> map = new BiMap<>();
        map.put("0", "KEY_NONE");
        map.put("1", "KEY_ESCAPE");
        map.put("2", "KEY_1");
        map.put("3", "KEY_2");
        map.put("4", "KEY_3");
        map.put("5", "KEY_4");
        map.put("6", "KEY_5");
        map.put("7", "KEY_6");
        map.put("8", "KEY_7");
        map.put("9", "KEY_8");
        map.put("10", "KEY_9");
        map.put("11", "KEY_0");
        map.put("12", "KEY_MINUS");
        map.put("13", "KEY_EQUALS");
        map.put("14", "KEY_BACK");
        map.put("15", "KEY_TAB");
        map.put("16", "KEY_Q");
        map.put("17", "KEY_W");
        map.put("18", "KEY_E");
        map.put("19", "KEY_R");
        map.put("20", "KEY_T");
        map.put("21", "KEY_Y");
        map.put("22", "KEY_U");
        map.put("23", "KEY_I");
        map.put("24", "KEY_O");
        map.put("25", "KEY_P");
        map.put("26", "KEY_LBRACKET");
        map.put("27", "KEY_RBRACKET");
        map.put("28", "KEY_RETURN");
        map.put("29", "KEY_LCONTROL");
        map.put("30", "KEY_A");
        map.put("31", "KEY_S");
        map.put("32", "KEY_D");
        map.put("33", "KEY_F");
        map.put("34", "KEY_G");
        map.put("35", "KEY_H");
        map.put("36", "KEY_J");
        map.put("37", "KEY_K");
        map.put("38", "KEY_L");
        map.put("39", "KEY_SEMICOLON");
        map.put("40", "KEY_APOSTROPHE");
        map.put("41", "KEY_GRAVE");
        map.put("42", "KEY_LSHIFT");
        map.put("43", "KEY_BACKSLASH");
        map.put("44", "KEY_Z");
        map.put("45", "KEY_X");
        map.put("46", "KEY_C");
        map.put("47", "KEY_V");
        map.put("48", "KEY_B");
        map.put("49", "KEY_N");
        map.put("50", "KEY_M");
        map.put("51", "KEY_COMMA");
        map.put("52", "KEY_PERIOD");
        map.put("53", "KEY_SLASH");
        map.put("54", "KEY_RSHIFT");
        map.put("55", "KEY_MULTIPLY");
        map.put("56", "KEY_LMENU");
        map.put("57", "KEY_SPACE");
        map.put("58", "KEY_CAPITAL");
        map.put("59", "KEY_F1");
        map.put("60", "KEY_F2");
        map.put("61", "KEY_F3");
        map.put("62", "KEY_F4");
        map.put("63", "KEY_F5");
        map.put("64", "KEY_F6");
        map.put("65", "KEY_F7");
        map.put("66", "KEY_F8");
        map.put("67", "KEY_F9");
        map.put("68", "KEY_F10");
        map.put("69", "KEY_NUMLOCK");
        map.put("70", "KEY_SCROLL");
        map.put("71", "KEY_NUMPAD7");
        map.put("72", "KEY_NUMPAD8");
        map.put("73", "KEY_NUMPAD9");
        map.put("74", "KEY_SUBTRACT");
        map.put("75", "KEY_NUMPAD4");
        map.put("76", "KEY_NUMPAD5");
        map.put("77", "KEY_NUMPAD6");
        map.put("78", "KEY_ADD");
        map.put("79", "KEY_NUMPAD1");
        map.put("80", "KEY_NUMPAD2");
        map.put("81", "KEY_NUMPAD3");
        map.put("82", "KEY_NUMPAD0");
        map.put("83", "KEY_DECIMAL");
        map.put("84", null);
        map.put("85", null);
        map.put("86", null);
        map.put("87", "KEY_F11");
        map.put("88", "KEY_F12");
        map.put("89", null);
        map.put("90", null);
        map.put("91", null);
        map.put("92", null);
        map.put("93", null);
        map.put("94", null);
        map.put("95", null);
        map.put("96", null);
        map.put("97", null);
        map.put("98", null);
        map.put("99", null);
        map.put("100", "KEY_F13");
        map.put("101", "KEY_F14");
        map.put("102", "KEY_F15");
        map.put("103", "KEY_F16");
        map.put("104", "KEY_F17");
        map.put("105", "KEY_F18");
        map.put("106", null);
        map.put("107", null);
        map.put("108", null);
        map.put("109", null);
        map.put("110", null);
        map.put("111", null);
        map.put("112", "KEY_KANA");
        map.put("113", "KEY_F19");
        map.put("114", null);
        map.put("115", null);
        map.put("116", null);
        map.put("117", null);
        map.put("118", null);
        map.put("119", null);
        map.put("120", null);
        map.put("121", "KEY_CONVERT");
        map.put("122", null);
        map.put("123", "KEY_NOCONVERT");
        map.put("124", null);
        map.put("125", "KEY_YEN");
        map.put("126", null);
        map.put("127", null);
        map.put("128", null);
        map.put("129", null);
        map.put("130", null);
        map.put("131", null);
        map.put("132", null);
        map.put("133", null);
        map.put("134", null);
        map.put("135", null);
        map.put("136", null);
        map.put("137", null);
        map.put("138", null);
        map.put("139", null);
        map.put("140", null);
        map.put("141", "KEY_NUMPADEQUALS");
        map.put("142", null);
        map.put("143", null);
        map.put("144", "KEY_CIRCUMFLEX");
        map.put("145", "KEY_AT");
        map.put("146", "KEY_COLON");
        map.put("147", "KEY_UNDERLINE");
        map.put("148", "KEY_KANJI");
        map.put("149", "KEY_STOP");
        map.put("150", "KEY_AX");
        map.put("151", "KEY_UNLABELED");
        map.put("152", null);
        map.put("153", null);
        map.put("154", null);
        map.put("155", null);
        map.put("156", "KEY_NUMPADENTER");
        map.put("157", "KEY_RCONTROL");
        map.put("158", null);
        map.put("159", null);
        map.put("160", null);
        map.put("161", null);
        map.put("162", null);
        map.put("163", null);
        map.put("164", null);
        map.put("165", null);
        map.put("166", null);
        map.put("167", "KEY_SECTION");
        map.put("168", null);
        map.put("169", null);
        map.put("170", null);
        map.put("171", null);
        map.put("172", null);
        map.put("173", null);
        map.put("174", null);
        map.put("175", null);
        map.put("176", null);
        map.put("177", null);
        map.put("178", null);
        map.put("179", "KEY_NUMPADCOMMA");
        map.put("180", null);
        map.put("181", "KEY_DIVIDE");
        map.put("182", null);
        map.put("183", "KEY_SYSRQ");
        map.put("184", "KEY_RMENU");
        map.put("185", null);
        map.put("186", null);
        map.put("187", null);
        map.put("188", null);
        map.put("189", null);
        map.put("190", null);
        map.put("191", null);
        map.put("192", null);
        map.put("193", null);
        map.put("194", null);
        map.put("195", null);
        map.put("196", "KEY_FUNCTION");
        map.put("197", "KEY_PAUSE");
        map.put("198", null);
        map.put("199", "KEY_HOME");
        map.put("200", "KEY_UP");
        map.put("201", "KEY_PRIOR");
        map.put("202", null);
        map.put("203", "KEY_LEFT");
        map.put("204", null);
        map.put("205", "KEY_RIGHT");
        map.put("206", null);
        map.put("207", "KEY_END");
        map.put("208", "KEY_DOWN");
        map.put("209", "KEY_NEXT");
        map.put("210", "KEY_INSERT");
        map.put("211", "KEY_DELETE");
        map.put("212", null);
        map.put("213", null);
        map.put("214", null);
        map.put("215", null);
        map.put("216", null);
        map.put("217", null);
        map.put("218", "KEY_CLEAR");
        map.put("219", "KEY_LMETA");
        map.put("220", "KEY_RMETA");
        map.put("221", "KEY_APPS");
        map.put("222", "KEY_POWER");
        map.put("223", "KEY_SLEEP");
        return map;
    }

    public static String findKeyString(int code) {
        return KEYCODE_MAP.get(String.valueOf(code));
    }
    public static int findKeycode(String name) {
        String code = KEYCODE_MAP.inverse(name);
        return code == null ? -1 : Integer.parseInt(code);
    }
    protected final Minecraft mc = Minecraft.getInstance();
    @Getter
    public Options keybinds = mc.options;
}
